"""Tests for the generate command and the header rendering."""

import re
from pathlib import Path

from click.testing import CliRunner

from codegen_cpp.cli import cli
from codegen_cpp.codegen import (
    CSV_READER_INCLUDES,
    CSV_WRITER_INCLUDES,
    aggregate_includes,
    arrow_type_expression,
    header_file,
    hdf5_includes,
    render_aggregate,
    render_csv_reader,
    render_csv_writer,
    render_dataset,
    render_hdf5_reader,
    render_hdf5_writer,
    render_parquet_reader,
    render_parquet_writer,
    render_spec,
    render_table,
)
from codegen_cpp.spec import (
    Column,
    CsvReader,
    CsvWriter,
    Dataset,
    Hdf5Reader,
    Hdf5Writer,
    Map,
    NdArray,
    ParquetReader,
    ParquetWriter,
    ScalarType,
    Struct,
    StructField,
    Table,
    Vector,
)

EXAMPLE = Path(__file__).parent.parent / "examples" / "table1.toml"

TABLE_SPEC = '[[table]]\nname = "Point"\ncolumns = [{ name = "id", type = "u32" }]\n'

TABLE = Table(
    name="Point",
    columns=[
        Column(name="id", type=ScalarType.u32),
        Column(name="label", type=ScalarType.str),
    ],
)


def test_render_table() -> None:
    """The rendered header declares a column store with a nested row struct."""
    header = render_table(TABLE)

    assert "struct Point {" in header
    assert "    struct row_type {" in header
    assert "        std::uint32_t id;" in header
    assert "        std::string label;" in header
    assert "    std::vector<std::uint32_t> id;" in header
    assert "    std::vector<std::string> label;" in header
    assert "void push_back(const row_type& row) {" in header
    assert "        const std::uint32_t& id_," in header
    assert "        const std::string& label_) {" in header
    assert "        id.push_back(id_);" in header
    assert "row_type operator[](std::size_t i) const {" in header
    assert "    Point() = default;" in header
    assert "    Point(const Point&) = delete;" in header
    assert "    Point& operator=(const Point&) = delete;" in header
    assert "    Point(Point&&) = default;" in header
    assert "    Point& operator=(Point&&) = default;" in header


def generate_into(tmp_path: Path, spec_file: Path) -> str:
    """Generate SPEC_FILE into TMP_PATH and return the header it wrote."""
    output_file = tmp_path / "spec.hpp"
    result = CliRunner().invoke(
        cli, ["generate", str(spec_file), "--output-file", str(output_file)]
    )

    assert result.exit_code == 0, result.output
    return output_file.read_text()


def definition_of(header: str, name: str) -> str:
    """
    Return the definition of NAME out of the single generated HEADER.

    Every definition opens in the first column and is closed there too,
    so the one declaring NAME runs from the line that names it
    down to the first line closing a block after it.
    """
    lines = header.split("\n")
    declaration = re.compile(rf"^(struct|class|inline) .*\b{re.escape(name)}\b")

    starts = [i for i, line in enumerate(lines) if declaration.match(line)]
    assert len(starts) == 1, f"'{name}' is not defined exactly once"
    start = starts[0]

    ends = [i for i in range(start, len(lines)) if lines[i].startswith("}")]
    assert ends, f"the definition of '{name}' is never closed"
    return "\n".join(lines[start : ends[0] + 1])


def test_generate_writes_one_header_for_the_whole_spec(tmp_path: Path) -> None:
    """Generate writes every section of the spec into a single header."""
    header = generate_into(tmp_path, EXAMPLE)

    assert sorted(p.name for p in tmp_path.iterdir()) == ["spec.hpp"]
    assert header.startswith("#pragma once\n")
    assert "// Generated by codegen-cpp from 'table1.toml'." in header
    assert "// Do not edit this file by hand." in header

    # Every section of the example is defined once, and only once.
    for declaration in (
        "struct Measurement {",
        "struct Station {",
        "class MeasurementCsvReader {",
        "class StationCsvReader {",
        "class MeasurementParquetReader {",
        "class MeasurementCsvWriter {",
        "class StationCsvWriter {",
        "class MeasurementParquetWriter {",
    ):
        assert header.count(declaration) == 1, declaration


def test_generate_declares_a_table_before_the_classes_over_it(tmp_path: Path) -> None:
    """A definition only ever names what an earlier definition declared."""
    header = generate_into(tmp_path, EXAMPLE)

    assert header.index("struct Measurement {") < header.index(
        "class MeasurementCsvReader {"
    )
    assert header.index("struct Station {") < header.index("class StationCsvWriter {")


def test_generate_includes_every_header_the_spec_needs_once(tmp_path: Path) -> None:
    """The includes of the sections are merged into one block per group."""
    header = generate_into(tmp_path, EXAMPLE)

    # The readers and the writers of the example ask for these in common.
    for include in ("#include <vector>", "#include <arrow/api.h>"):
        assert header.count(include) == 1, include

    # The standard library is listed first, and each group is sorted.
    includes = [line for line in header.split("\n") if line.startswith("#include")]
    assert includes.index("#include <vector>") < includes.index(
        "#include <arrow/api.h>"
    )
    assert includes == sorted(includes, key=lambda line: ("/" in line, line))

    # Nothing is included by name, because there is no other header to name.
    assert '#include "' not in header


def test_generate_names_the_header_after_the_spec(tmp_path: Path) -> None:
    """Without an output file the header takes the name of the spec."""
    spec_file = tmp_path / "points.toml"
    spec_file.write_text(TABLE_SPEC)

    result = CliRunner().invoke(cli, ["generate", str(spec_file)])

    assert result.exit_code == 0, result.output
    assert sorted(p.name for p in tmp_path.iterdir()) == ["points.hpp", "points.toml"]
    assert "struct Point {" in (tmp_path / "points.hpp").read_text()


def test_header_file_replaces_the_toml_suffix() -> None:
    """The default header sits beside the spec it is generated from."""
    assert header_file(Path("spec/points.toml")) == Path("spec/points.hpp")


def test_generate_overwrites_the_output_file(tmp_path: Path) -> None:
    """An output file that is already there is replaced, not appended to."""
    output_file = tmp_path / "spec.hpp"
    output_file.write_text("// stale\n")

    result = CliRunner().invoke(
        cli, ["generate", str(EXAMPLE), "--output-file", str(output_file)]
    )

    assert result.exit_code == 0, result.output
    assert "stale" not in output_file.read_text()


def test_generate_creates_the_directories_of_the_output_file(tmp_path: Path) -> None:
    """Generate creates the directories of the output file when they are missing."""
    output_file = tmp_path / "nested" / "include" / "spec.hpp"
    result = CliRunner().invoke(cli, ["generate", str(EXAMPLE), "-o", str(output_file)])

    assert result.exit_code == 0, result.output
    assert "struct Measurement {" in output_file.read_text()


def test_generate_rejects_a_directory_as_the_output_file(tmp_path: Path) -> None:
    """The output flag takes a file, so a directory is reported as an error."""
    result = CliRunner().invoke(cli, ["generate", str(EXAMPLE), "-o", str(tmp_path)])

    assert result.exit_code != 0


def test_generate_reports_invalid_spec(tmp_path: Path) -> None:
    """An invalid spec is reported as an error instead of a traceback."""
    spec_file = tmp_path / "spec.toml"
    spec_file.write_text('[[table]]\nname = "t"\ncolumns = []\n')

    result = CliRunner().invoke(
        cli, ["generate", str(spec_file), "-o", str(tmp_path / "spec.hpp")]
    )

    assert result.exit_code != 0
    assert "has no columns" in result.output
    assert not (tmp_path / "spec.hpp").exists()


READER = CsvReader(
    name="PointReader",
    table="Point",
    default={"label": "n/a"},
)


def test_render_csv_reader() -> None:
    """The rendered header defines a reader class over the table header."""
    header = render_csv_reader(READER, TABLE)

    assert "class PointReader {" in header
    assert "PointReader(const std::string& csv_file, std::size_t batch_size," in header
    assert "bool use_threads = false," in header
    assert "std::int32_t block_size = default_block_size," in header
    assert "std::optional<arrow::Compression::type> compression =" in header
    assert "std::nullopt)" in header
    assert "std::int32_t default_block_size = 128 * 1024 * 1024;" in header
    assert "bool has_more_batches() {" in header
    assert "void read_batch(Point& table) {" in header
    assert "void read_all(Point& table) {" in header


def test_render_csv_reader_reads_batches_through_one_helper() -> None:
    """read_batch and read_all copy the rows of a batch with the same helper."""
    header = render_csv_reader(READER, TABLE)

    assert "std::int64_t append_rows(Point& table, std::int64_t wanted) {" in header
    assert header.count("static_cast<const arrow::UInt32Array*>(") == 1

    # read_batch stops at batch_size rows; read_all takes whatever is left.
    assert "appended += append_rows(table, wanted - appended);" in header
    assert "append_rows(table, batch_->num_rows() - offset_);" in header


def test_render_csv_reader_column_types() -> None:
    """The reader pins the Arrow types of the columns it reads."""
    header = render_csv_reader(READER, TABLE)

    assert '"id",' in header
    assert '{"id", arrow::uint32()},' in header
    assert '{"label", arrow::utf8()},' in header
    assert "static_cast<const arrow::UInt32Array*>(" in header
    assert "static_cast<const arrow::StringArray*>(" in header


def test_render_csv_reader_null_handling() -> None:
    """Only the columns that are not nullable are checked for nulls."""
    header = render_csv_reader(READER, TABLE)

    # 'id' is column 0 and is not nullable; 'label' is column 1 and is.
    assert "if (batch.column(0)->null_count() != 0) [[unlikely]] {" in header
    assert "\"column 'id' contains null values\"" in header
    assert "if (batch.column(1)->null_count() != 0) {" not in header

    # Nulls of a nullable column are read as the default value.
    assert "column_id->Value(i)," in header
    assert (
        'column_label->IsNull(i) ? std::string("n/a") '
        ": column_label->GetString(i)" in header
    )


def test_render_csv_reader_default_section() -> None:
    """A CSV reader takes its defaults keyed by column, as a Parquet one does."""
    reader = CsvReader(name="PointReader", table="Point", default={"label": "n/a"})

    header = render_csv_reader(reader, TABLE)

    assert "column_id->Value(i)," in header
    assert (
        'column_label->IsNull(i) ? std::string("n/a") '
        ": column_label->GetString(i)" in header
    )
    assert "\"column 'label' contains null values\"" not in header


def test_render_csv_reader_names_a_column_in_the_file() -> None:
    """A reader looks for the name the file gives a column."""
    reader = CsvReader(name="PointReader", table="Point", name_in_file={"id": "Ident"})

    header = render_csv_reader(reader, TABLE)

    # The file is asked for the name it uses, in the declared order.
    assert '            "Ident",\n            "label",\n' in header
    assert '{"Ident", arrow::uint32()},' in header
    assert '{"label", arrow::utf8()},' in header

    # The table is still filled in through the name that declares the column.
    assert "column_id->Value(i)," in header
    assert "\"column 'id' contains null values\"" in header


def test_render_csv_reader_escapes_the_name_in_the_file() -> None:
    """A file names a column however it likes; the header still compiles."""
    reader = CsvReader(name="PointReader", table="Point", name_in_file={"id": 'a"b\\c'})

    header = render_csv_reader(reader, TABLE)

    assert r'"a\"b\\c",' in header
    assert r'{"a\"b\\c", arrow::uint32()},' in header


def test_generate_defines_every_csv_reader(tmp_path: Path) -> None:
    """Generate defines a class for every CSV reader of the spec."""
    header = generate_into(tmp_path, EXAMPLE)

    reader = definition_of(header, "MeasurementCsvReader")
    assert reader.startswith("class MeasurementCsvReader {")
    assert "void read_batch(Measurement& table) {" in reader
    assert "void read_all(Measurement& table) {" in reader


PARQUET_READER = ParquetReader(
    name="PointParquetReader",
    table="Point",
    default={"label": "n/a"},
)


def test_render_parquet_reader() -> None:
    """The rendered header defines a reader class over the table header."""
    header = render_parquet_reader(PARQUET_READER, TABLE)

    assert "class PointParquetReader {" in header
    assert "PointParquetReader(const std::string& parquet_file," in header
    assert "std::size_t batch_size," in header
    assert "std::int64_t buffer_size = default_buffer_size)" in header
    assert "bool has_more_batches() {" in header
    assert "void read_batch(Point& table) {" in header
    assert "void read_all(Point& table) {" in header


def test_render_parquet_reader_reads_batches_through_one_helper() -> None:
    """read_batch and read_all copy the rows of a batch with the same helper."""
    header = render_parquet_reader(PARQUET_READER, TABLE)

    assert "std::int64_t append_rows(Point& table, std::int64_t wanted) {" in header
    assert header.count("static_cast<const arrow::UInt32Array*>(") == 1

    # read_batch stops at batch_size rows; read_all takes whatever is left.
    assert "appended += append_rows(table, wanted - appended);" in header
    assert "append_rows(table, batch_->num_rows() - offset_);" in header


def test_render_parquet_reader_sets_the_buffer_size() -> None:
    """The reader reads through a buffer of the size it is given."""
    header = render_parquet_reader(PARQUET_READER, TABLE)

    assert (
        "static constexpr std::int64_t default_buffer_size = 128 * 1024 * 1024;"
        in header
    )
    assert "if (buffer_size <= 0) [[unlikely]] {" in header
    assert "parquet::ReaderProperties reader_properties(" in header
    assert "reader_properties.enable_buffered_stream();" in header
    assert "reader_properties.set_buffer_size(buffer_size);" in header


def test_render_parquet_reader_reads_record_batches() -> None:
    """The reader projects the columns it needs and reads record batches."""
    header = render_parquet_reader(PARQUET_READER, TABLE)

    assert "parquet::arrow::FileReaderBuilder builder;" in header
    assert "builder.Open(std::move(input), reader_properties)" in header
    assert "reader_->set_batch_size(" in header
    assert 'field_index(*schema, "id", arrow::uint32()),' in header
    assert 'field_index(*schema, "label", arrow::utf8()),' in header
    assert "reader_->GetRecordBatchReader(row_groups, columns)" in header
    assert "batches_->ReadNext(&batch)" in header
    assert "static_cast<const arrow::UInt32Array*>(" in header
    assert "static_cast<const arrow::StringArray*>(" in header


def test_render_parquet_reader_checks_the_schema() -> None:
    """The reader verifies the columns it is given, in order."""
    header = render_parquet_reader(PARQUET_READER, TABLE)

    assert "if (schema.num_fields() != 2) [[unlikely]] {" in header
    assert 'if (schema.field(0)->name() != "id") [[unlikely]] {' in header
    assert 'if (schema.field(1)->name() != "label") [[unlikely]] {' in header


def test_render_parquet_reader_null_handling() -> None:
    """Only the columns that are not nullable are checked for nulls."""
    header = render_parquet_reader(PARQUET_READER, TABLE)

    assert "if (batch.column(0)->null_count() != 0) [[unlikely]] {" in header
    assert "\"column 'id' of '\"" in header
    assert "if (batch.column(1)->null_count() != 0) {" not in header

    assert "column_id->Value(i)," in header
    assert (
        'column_label->IsNull(i) ? std::string("n/a") '
        ": column_label->GetString(i)" in header
    )


def test_generate_defines_every_parquet_reader(tmp_path: Path) -> None:
    """Generate defines a class for every Parquet reader of the spec."""
    header = generate_into(tmp_path, EXAMPLE)

    reader = definition_of(header, "MeasurementParquetReader")
    assert reader.startswith("class MeasurementParquetReader {")
    assert "void read_batch(Measurement& table) {" in reader
    assert "void read_all(Measurement& table) {" in reader


WRITER = CsvWriter(name="PointCsvWriter", table="Point")


def test_render_csv_writer() -> None:
    """The rendered header defines a writer class over the table header."""
    header = render_csv_writer(WRITER, TABLE)

    assert "class PointCsvWriter {" in header
    assert "explicit PointCsvWriter(" in header
    assert "const std::string& csv_file," in header
    assert (
        "std::optional<arrow::Compression::type> compression = std::nullopt," in header
    )
    assert "int compression_level = arrow::util::kUseDefaultCompressionLevel)" in header
    assert "void write_batch(const Point& table) {" in header
    assert "void close() {" in header
    assert "~PointCsvWriter() {" in header


def test_render_csv_writer_builds_every_column() -> None:
    """Every column is built with the Arrow builder of its type."""
    header = render_csv_writer(WRITER, TABLE)

    assert 'arrow::field("id", arrow::uint32()),' in header
    assert 'arrow::field("label", arrow::utf8()),' in header
    assert "arrow::UInt32Builder builder_id;" in header
    assert "arrow::StringBuilder builder_label;" in header
    assert "builder_id.AppendValues(table.id)" in header
    assert "builder_label.AppendValues(table.label)" in header
    assert "writer_->WriteRecordBatch(*batch)" in header


RENAMING_WRITER = CsvWriter(
    name="PointCsvWriter", table="Point", name_in_file={"id": "Point ID"}
)


def test_render_csv_writer_writes_the_names_of_the_file() -> None:
    """A renamed column is written under the name the file is to give it."""
    header = render_csv_writer(RENAMING_WRITER, TABLE)

    assert 'arrow::field("Point ID", arrow::uint32()),' in header
    assert 'arrow::field("label", arrow::utf8()),' in header

    # The C++ member keeps the name that the table gives it.
    assert "builder_id.AppendValues(table.id)" in header


def test_generate_defines_every_csv_writer(tmp_path: Path) -> None:
    """Generate defines a class for every CSV writer of the spec."""
    spec_file = tmp_path / "points.toml"
    spec_file.write_text(
        TABLE_SPEC + '\n[[csv_writer]]\nname = "PointCsvWriter"\ntable = "Point"\n'
    )

    header = generate_into(tmp_path, spec_file)

    assert definition_of(header, "Point").startswith("struct Point {")
    assert definition_of(header, "PointCsvWriter").startswith("class PointCsvWriter {")


PARQUET_WRITER = ParquetWriter(name="PointParquetWriter", table="Point")


def test_render_parquet_writer() -> None:
    """The rendered header defines a writer class over the table header."""
    header = render_parquet_writer(PARQUET_WRITER, TABLE)

    assert "class PointParquetWriter {" in header
    assert "explicit PointParquetWriter(" in header
    assert "const std::string& parquet_file," in header
    assert "void write_batch(const Point& table) {" in header
    assert "void close() {" in header
    assert "~PointParquetWriter() {" in header


def test_render_parquet_writer_writes_record_batches() -> None:
    """The writer builds the columns and writes them as record batches."""
    header = render_parquet_writer(PARQUET_WRITER, TABLE)

    assert 'arrow::field("id", arrow::uint32()),' in header
    assert "arrow::UInt32Builder builder_id;" in header
    assert "arrow::StringBuilder builder_label;" in header
    assert "parquet::arrow::FileWriter::Open(" in header
    assert ".compression(compression)" in header
    assert "arrow::Compression::type compression = arrow::Compression::ZSTD" in header
    assert "std::int64_t default_row_group_length = 128000;" in header
    assert "writer_->WriteRecordBatch(*batch)" in header


def test_render_parquet_writer_writes_the_names_of_the_file() -> None:
    """A renamed column is written under the name the file is to give it."""
    writer = ParquetWriter(
        name="PointParquetWriter", table="Point", name_in_file={"id": "Point ID"}
    )
    header = render_parquet_writer(writer, TABLE)

    assert 'arrow::field("Point ID", arrow::uint32()),' in header
    assert 'arrow::field("label", arrow::utf8()),' in header
    assert "builder_id.AppendValues(table.id)" in header


def test_generate_defines_every_parquet_writer(tmp_path: Path) -> None:
    """Generate defines a class for every Parquet writer of the spec."""
    spec_file = tmp_path / "points.toml"
    spec_file.write_text(
        TABLE_SPEC
        + '\n[[parquet_writer]]\nname = "PointParquetWriter"\ntable = "Point"\n'
    )

    header = generate_into(tmp_path, spec_file)

    assert definition_of(header, "Point").startswith("struct Point {")
    assert definition_of(header, "PointParquetWriter").startswith(
        "class PointParquetWriter {"
    )


def test_render_csv_reader_infers_the_compression() -> None:
    """The reader guesses the codec from the name of the file it reads."""
    header = render_csv_reader(READER, TABLE)

    assert "arrow/io/compressed.h" in CSV_READER_INCLUDES.external
    assert 'if (path.ends_with(".gz")) {' in header
    assert "return arrow::Compression::GZIP;" in header
    assert 'if (path.ends_with(".zst")) {' in header
    assert "return arrow::Compression::ZSTD;" in header
    assert "compression.value_or(compression_of(csv_file_))" in header
    assert "arrow::io::CompressedInputStream::Make(codec_.get(), input)" in header


def test_render_csv_writer_infers_the_compression() -> None:
    """The writer guesses the codec from the name of the file it writes."""
    header = render_csv_writer(WRITER, TABLE)

    assert "arrow/io/compressed.h" in CSV_WRITER_INCLUDES.external
    assert 'if (path.ends_with(".gz")) {' in header
    assert "return arrow::Compression::ZSTD;" in header
    assert "compression.value_or(compression_of(csv_file_))" in header
    assert "arrow::util::CodecOptions(compression_level)" in header
    assert "arrow::io::CompressedOutputStream::Make(codec_.get(), output_)" in header


DATASET_EXAMPLE = Path(__file__).parent.parent / "examples" / "dataset1.toml"

DATASET = Dataset(
    name="TileData",
    dims=["row", "col"],
    arrays=[
        NdArray(name="burn_time", type=ScalarType.f32),
        NdArray(name="state", type=ScalarType.i8),
    ],
)


def test_render_dataset() -> None:
    """The rendered header defines a struct of mdspans over owned memory."""
    header = render_dataset(DATASET)

    assert "struct TileData {" in header
    assert "static constexpr std::size_t rank = 2;" in header
    assert "std::vector<std::size_t> dims;" in header

    # Every array owns its memory and hands out an mdspan over it.
    assert "std::unique_ptr<float[]> _mem_burn_time;" in header
    assert "span_type<float> burn_time;" in header
    assert "std::unique_ptr<std::int8_t[]> _mem_state;" in header
    assert "span_type<std::int8_t> state;" in header


def test_render_dataset_constructor_takes_every_dim() -> None:
    """The constructor takes one size per dimension and allocates the arrays."""
    header = render_dataset(DATASET)

    assert "TileData(" in header
    assert "        std::size_t row," in header
    assert "        std::size_t col)" in header
    assert ": dims{row, col}," in header
    assert "std::make_unique_for_overwrite<float[]>(" in header
    assert "burn_time(_mem_burn_time.get(), row, col)," in header
    assert "state(_mem_state.get(), row, col) {" in header


def test_render_dataset_is_row_major_by_default() -> None:
    """Without `column_major` the arrays are stored row major."""
    header = render_dataset(DATASET)

    assert "std::experimental::layout_right>;" in header
    assert "stored in row major order" in header
    assert "so 'col' varies fastest" in header
    assert "layout_left" not in header


def test_render_dataset_column_major() -> None:
    """With `column_major` the arrays are stored column major."""
    header = render_dataset(DATASET.model_copy(update={"column_major": True}))

    assert "std::experimental::layout_left>;" in header
    assert "stored in column major order" in header
    assert "so 'row' varies fastest" in header
    assert "layout_right" not in header


def test_render_dataset_is_not_copyable() -> None:
    """A dataset owns its memory, so it may not be copied."""
    header = render_dataset(DATASET)

    assert "TileData(const TileData&) = delete;" in header
    assert "TileData& operator=(const TileData&) = delete;" in header


def test_render_dataset_of_every_rank() -> None:
    """The rank of the mdspan follows the number of dims."""
    for dims in (["tick"], ["row", "col"], ["tick", "row", "col"]):
        dataset = Dataset(
            name="D",
            dims=dims,
            arrays=[NdArray(name="a", type=ScalarType.f64)],
        )
        header = render_dataset(dataset)

        assert f"static constexpr std::size_t rank = {len(dims)};" in header
        arguments = ", ".join(dims)
        assert f"a(_mem_a.get(), {arguments}) {{" in header


def test_generate_defines_every_dataset(tmp_path: Path) -> None:
    """Generate defines a struct for every dataset of the spec."""
    header = generate_into(tmp_path, DATASET_EXAMPLE)

    for name in ("Series", "Raster", "Volume"):
        assert definition_of(header, name).startswith(f"struct {name} {{")

    # Only Volume asks for column major storage in the example.
    assert "layout_right" in definition_of(header, "Raster")
    assert "layout_left" in definition_of(header, "Volume")


HDF5_READER = Hdf5Reader(name="read_tile_data", dataset="TileData")


def test_render_hdf5_reader() -> None:
    """The rendered header defines a function over the dataset header."""
    header = render_hdf5_reader(HDF5_READER, DATASET)

    assert "inline void read_tile_data(H5::H5File& file," in header
    assert "const std::string& group_path," in header
    assert "TileData& data) {" in header
    assert "const H5::Group group = file.openGroup(group_path);" in header


def test_render_hdf5_reader_declares_nothing_but_the_function() -> None:
    """The macros expand in place, so the header holds one function."""
    header = render_hdf5_reader(HDF5_READER, DATASET)

    # Everything else is a comment, an include, or indented inside the body.
    top_level = [
        line
        for line in header.splitlines()
        if line and not line.startswith((" ", "}", "#", "//"))
    ]
    assert len(top_level) == 1
    assert top_level[0].startswith("inline void read_tile_data(")

    assert "namespace" not in header
    assert "template" not in header


def test_render_hdf5_reader_reads_every_array_by_default() -> None:
    """Without include or exclude every array of the dataset is read."""
    header = render_hdf5_reader(HDF5_READER, DATASET)

    assert 'const std::string path = group_path + "/burn_time";' in header
    assert 'const std::string path = group_path + "/state";' in header
    assert 'if (!group.nameExists("burn_time")) [[unlikely]] {' in header
    assert 'const H5::DataSet array = group.openDataSet("state");' in header


def test_render_hdf5_reader_include() -> None:
    """An include list reads only the arrays it names."""
    reader = Hdf5Reader(name="read_seed", dataset="TileData", include=["state"])
    header = render_hdf5_reader(reader, DATASET)

    assert 'const std::string path = group_path + "/state";' in header
    assert "burn_time" not in header
    assert "// Read the array state" in header


def test_render_hdf5_reader_exclude() -> None:
    """An exclude list reads every array it does not name."""
    reader = Hdf5Reader(name="read_rest", dataset="TileData", exclude=["state"])
    header = render_hdf5_reader(reader, DATASET)

    assert 'const std::string path = group_path + "/burn_time";' in header
    assert "state" not in header


def test_render_hdf5_reader_pins_the_datatypes() -> None:
    """Every array is checked against the predefined type it declares."""
    header = render_hdf5_reader(HDF5_READER, DATASET)

    assert "const H5::DataType stored = array.getDataType();" in header
    assert "if (stored != H5::PredType::NATIVE_FLOAT) [[unlikely]] {" in header
    assert "if (stored != H5::PredType::NATIVE_INT8) [[unlikely]] {" in header
    assert "\"' is not stored as 'f32'\");" in header
    assert "\"' is not stored as 'i8'\");" in header

    # One comparison covers every property, so none is spelled out by hand.
    assert "H5T_" not in header
    assert "getClass()" not in header
    assert "getSign()" not in header


def test_render_hdf5_reader_checks_the_shape() -> None:
    """The rank and every extent are checked against the allocated dataset."""
    header = render_hdf5_reader(HDF5_READER, DATASET)

    assert "const H5::DataSpace space = array.getSpace();" in header
    assert "if (space.getSimpleExtentNdims() != 2) [[unlikely]] {" in header
    assert "std::array<hsize_t, TileData::rank> extents;" in header
    assert "space.getSimpleExtentDims(extents.data());" in header
    assert "for (std::size_t i = 0; i < TileData::rank; ++i) {" in header
    assert "const hsize_t declared = static_cast<hsize_t>(data.dims[i]);" in header
    assert "if (extents[i] != declared) [[unlikely]] {" in header


def test_render_hdf5_reader_of_an_unsigned_array() -> None:
    """An unsigned array is checked against the unsigned predefined type."""
    dataset = Dataset(
        name="Counts",
        dims=["row"],
        arrays=[NdArray(name="hits", type=ScalarType.u16)],
    )
    reader = Hdf5Reader(name="read_counts", dataset="Counts")
    header = render_hdf5_reader(reader, dataset)

    assert "if (stored != H5::PredType::NATIVE_UINT16) [[unlikely]] {" in header
    assert "H5T_" not in header


def test_render_hdf5_reader_reports_errors_as_runtime_errors() -> None:
    """Everything that goes wrong is reported as a std::runtime_error."""
    header = render_hdf5_reader(HDF5_READER, DATASET)

    assert "} catch (const H5::Exception& e) {" in header
    assert 'throw std::runtime_error("failed to read \'" + group_path + "\': " +' in (
        header
    )
    assert '"\' is not in the HDF5 file");' in header


def test_render_hdf5_reader_of_a_row_major_dataset_reads_in_place() -> None:
    """A row major dataset is stored the way HDF5 reads, so it reads directly."""
    header = render_hdf5_reader(HDF5_READER, DATASET)

    assert "array.read(data._mem_burn_time.get()," in header
    assert "H5::PredType::NATIVE_FLOAT);" in header
    assert "buffer" not in header
    assert "vector" not in hdf5_includes(DATASET).std


def test_render_hdf5_reader_of_a_column_major_dataset_lays_out_again() -> None:
    """A column major dataset of rank two or more is laid out after reading."""
    column_major = DATASET.model_copy(update={"column_major": True})
    header = render_hdf5_reader(HDF5_READER, column_major)

    assert "vector" in hdf5_includes(column_major).std
    assert "std::vector<float> buffer(data.size());" in header
    assert "array.read(buffer.data(), H5::PredType::NATIVE_FLOAT);" in header
    assert "std::size_t element = 0;" in header
    assert "for (std::size_t i0 = 0; i0 < data.dims[0]; ++i0) {" in header
    assert "for (std::size_t i1 = 0; i1 < data.dims[1]; ++i1) {" in header
    assert "data.burn_time[i0, i1] = buffer[element++];" in header


def test_render_hdf5_reader_unrolls_the_loops_of_every_rank() -> None:
    """The rank is known when the header is written, so the loops are unrolled."""
    dataset = Dataset(
        name="SimOutput",
        dims=["tick", "row", "col"],
        arrays=[NdArray(name="state", type=ScalarType.i8)],
        column_major=True,
    )
    reader = Hdf5Reader(name="read_sim_output", dataset="SimOutput")
    header = render_hdf5_reader(reader, dataset)

    assert "for (std::size_t i2 = 0; i2 < data.dims[2]; ++i2) {" in header
    assert "data.state[i0, i1, i2] = buffer[element++];" in header
    assert "for (std::size_t i3" not in header


def test_render_hdf5_reader_of_a_one_dimensional_dataset_reads_in_place() -> None:
    """Rank one is the same either way, so it reads directly."""
    dataset = Dataset(
        name="TickData",
        dims=["tick"],
        arrays=[NdArray(name="wind_speed", type=ScalarType.f32)],
    )
    reader = Hdf5Reader(name="read_tick_data", dataset="TickData")
    header = render_hdf5_reader(reader, dataset)

    assert "array.read(data._mem_wind_speed.get()," in header
    assert "buffer" not in header


def test_generate_defines_every_hdf5_reader(tmp_path: Path) -> None:
    """Generate defines a function for every HDF5 reader of the spec."""
    header = generate_into(tmp_path, DATASET_EXAMPLE)

    reader = definition_of(header, "read_raster")
    assert reader.startswith("inline void read_raster(H5::H5File& file,")

    # 'read_raster_layers' excludes 'mask' and 'read_raster_mask' has only it.
    assert "mask" not in definition_of(header, "read_raster_layers")
    assert "elevation" not in definition_of(header, "read_raster_mask")

    # Only the reader of the column major dataset lays the elements out again.
    assert "buffer" in definition_of(header, "read_volume")
    assert "buffer" not in reader


HDF5_WRITER = Hdf5Writer(name="write_tile_data", dataset="TileData")


def test_render_hdf5_writer() -> None:
    """The rendered header defines a function over the dataset header."""
    header = render_hdf5_writer(HDF5_WRITER, DATASET)

    assert "inline void write_tile_data(H5::H5File& file," in header
    assert "const std::string& group_path," in header
    assert "const TileData& data) {" in header


def test_render_hdf5_writer_declares_nothing_but_the_function() -> None:
    """The macros expand in place, so the header holds one function."""
    header = render_hdf5_writer(HDF5_WRITER, DATASET)

    top_level = [
        line
        for line in header.splitlines()
        if line and not line.startswith((" ", "}", "#", "//"))
    ]
    assert len(top_level) == 1
    assert top_level[0].startswith("inline void write_tile_data(")

    assert "namespace" not in header
    assert "template" not in header


def test_render_hdf5_writer_creates_the_groups_that_are_missing() -> None:
    """The path is walked a name at a time, creating what is not there."""
    header = render_hdf5_writer(HDF5_WRITER, DATASET)

    assert 'H5::Group group = file.openGroup("/");' in header
    assert "const std::size_t end = group_path.find('/', begin);" in header
    assert "group = group.nameExists(name) ? group.openGroup(name)" in header
    assert ": group.createGroup(name);" in header


def test_render_hdf5_writer_replaces_an_array_that_is_there() -> None:
    """An array the group already holds is unlinked and created again."""
    header = render_hdf5_writer(HDF5_WRITER, DATASET)

    assert 'if (group.nameExists("burn_time")) {' in header
    assert 'group.unlink("burn_time");' in header
    assert "const H5::DataSet array = group.createDataSet(" in header
    assert '"burn_time", H5::PredType::NATIVE_FLOAT, space);' in header


def test_render_hdf5_writer_builds_one_dataspace_for_every_array() -> None:
    """Every array shares the shape data was allocated with."""
    header = render_hdf5_writer(HDF5_WRITER, DATASET)

    assert "std::array<hsize_t, TileData::rank> extents;" in header
    assert "extents[i] = static_cast<hsize_t>(data.dims[i]);" in header
    assert "const H5::DataSpace space(static_cast<int>(TileData::rank)," in header


def test_render_hdf5_writer_include() -> None:
    """An include list writes only the arrays it names."""
    writer = Hdf5Writer(name="write_seed", dataset="TileData", include=["state"])
    header = render_hdf5_writer(writer, DATASET)

    assert 'group.createDataSet(\n                "state"' in header
    assert "burn_time" not in header
    assert "// Write the array state" in header


def test_render_hdf5_writer_exclude() -> None:
    """An exclude list writes every array it does not name."""
    writer = Hdf5Writer(name="write_rest", dataset="TileData", exclude=["state"])
    header = render_hdf5_writer(writer, DATASET)

    assert "burn_time" in header
    assert "state" not in header


def test_render_hdf5_writer_of_a_row_major_dataset_writes_in_place() -> None:
    """A row major dataset is stored the way HDF5 writes, so it goes as it is."""
    header = render_hdf5_writer(HDF5_WRITER, DATASET)

    assert "array.write(data._mem_burn_time.get()," in header
    assert "buffer" not in header
    assert "vector" not in hdf5_includes(DATASET).std


def test_render_hdf5_writer_of_a_column_major_dataset_gathers_first() -> None:
    """A column major dataset of rank two or more is gathered before writing."""
    column_major = DATASET.model_copy(update={"column_major": True})
    header = render_hdf5_writer(HDF5_WRITER, column_major)

    assert "vector" in hdf5_includes(column_major).std
    assert "std::vector<float> buffer(data.size());" in header
    assert "for (std::size_t i0 = 0; i0 < data.dims[0]; ++i0) {" in header
    assert "buffer[element++] = data.burn_time[i0, i1];" in header
    assert "array.write(buffer.data(), H5::PredType::NATIVE_FLOAT);" in header


def test_render_hdf5_writer_reports_errors_as_runtime_errors() -> None:
    """Everything that goes wrong is reported as a std::runtime_error."""
    header = render_hdf5_writer(HDF5_WRITER, DATASET)

    assert "} catch (const H5::Exception& e) {" in header
    assert 'throw std::runtime_error("failed to write \'" + group_path' in header


def test_generate_defines_every_hdf5_writer(tmp_path: Path) -> None:
    """Generate defines a function for every HDF5 writer of the spec."""
    header = generate_into(tmp_path, DATASET_EXAMPLE)

    writer = definition_of(header, "write_raster")
    assert writer.startswith("inline void write_raster(H5::H5File& file,")
    assert "const Raster& data) {" in writer

    # The lists narrow a writer the same way they narrow a reader.
    assert "mask" not in definition_of(header, "write_raster_layers")
    assert "elevation" not in definition_of(header, "write_raster_mask")


def throw_only_ifs_without_the_hint(header: str) -> list[str]:
    """
    Return the `if` statements of HEADER that throw without `[[unlikely]]`.

    An `if` counts when the block it opens holds one `throw` and nothing
    else, which is the shape the templates are asked to annotate.
    """
    lines = header.split("\n")
    missing: list[str] = []
    for index, line in enumerate(lines):
        stripped = line.strip()
        if not stripped.startswith("if (") or not stripped.endswith("{"):
            continue

        indent = len(line) - len(line.lstrip())
        end = index + 1
        while (
            end < len(lines)
            and lines[end].strip() != "}"
            or (
                end < len(lines)
                and len(lines[end]) - len(lines[end].lstrip()) != indent
            )
        ):
            end += 1
            if end >= len(lines):
                break

        first = index + 1
        body = " ".join(
            b.strip()
            for b in lines[first:end]
            if b.strip() and not b.strip().startswith("//")
        )
        throws_only = body.startswith("throw") and body.count(";") == 1
        if throws_only and "[[unlikely]]" not in stripped:
            missing.append(stripped)
    return missing


def test_every_generated_throw_is_marked_unlikely() -> None:
    """A branch that only throws is annotated in every generated header."""
    headers = [
        render_table(TABLE),
        render_dataset(DATASET),
        render_csv_reader(READER, TABLE),
        render_csv_writer(WRITER, TABLE),
        render_parquet_reader(PARQUET_READER, TABLE),
        render_parquet_writer(PARQUET_WRITER, TABLE),
        render_hdf5_reader(HDF5_READER, DATASET),
        render_hdf5_writer(HDF5_WRITER, DATASET),
    ]

    for header in headers:
        assert throw_only_ifs_without_the_hint(header) == []


def test_the_hint_is_not_put_on_branches_that_do_more() -> None:
    """A branch that does something other than throw is left alone."""
    header = render_csv_reader(READER, TABLE)

    # These return or fall through instead of throwing.
    assert "if (batch_ == nullptr) {" in header
    assert 'if (path.ends_with(".gz")) {' in header
    assert "if (done_) {" in header


AGGREGATES_EXAMPLE = Path(__file__).parent.parent / "examples" / "table2.toml"

NESTED_TYPES = {
    "Tags": Vector(name="Tags", element=ScalarType.str),
    "Counts": Map(name="Counts", key=ScalarType.str, value=ScalarType.i64),
    "Spot": Struct(
        name="Spot",
        fields=[
            StructField(name="x", type=ScalarType.i32),
            StructField(name="tags", type="Tags"),
        ],
    ),
}

NESTED_TABLE = Table(
    name="Row",
    columns=[
        Column(name="id", type=ScalarType.u32),
        Column(name="tags", type="Tags"),
        Column(name="counts", type="Counts"),
        Column(name="spot", type="Spot"),
    ],
)

NESTED_READER = ParquetReader(
    name="RowParquetReader",
    table="Row",
    default={"tags.element": "n/a"},
    name_in_file={"spot.x": "across"},
)

NESTED_WRITER = ParquetWriter(name="RowParquetWriter", table="Row")


def test_render_aggregate_types() -> None:
    """Each aggregate type is written under the name that declares it."""
    assert "using Tags = std::vector<std::string>;" in render_aggregate(
        NESTED_TYPES["Tags"]
    )
    assert "using Counts = std::map<std::string, std::int64_t>;" in render_aggregate(
        NESTED_TYPES["Counts"]
    )

    struct = render_aggregate(NESTED_TYPES["Spot"])
    assert "struct Spot {" in struct
    assert "    std::int32_t x;" in struct
    assert "    Tags tags;" in struct
    assert "    bool operator==(const Spot&) const = default;" in struct


def test_render_an_unordered_map() -> None:
    """is_unordered picks the container, and nothing else."""
    unordered = Map(
        name="Counts", key=ScalarType.str, value=ScalarType.i64, is_unordered=True
    )

    assert (
        "using Counts = std::unordered_map<std::string, std::int64_t>;"
        in render_aggregate(unordered)
    )


def test_arrow_type_expression() -> None:
    """An aggregate type is stored as the Parquet shape it declares."""
    assert arrow_type_expression(ScalarType.i32, {}) == "arrow::int32()"
    assert (
        arrow_type_expression("Tags", NESTED_TYPES)
        == 'arrow::list(arrow::field("element", arrow::utf8()))'
    )
    assert (
        arrow_type_expression("Counts", NESTED_TYPES)
        == 'arrow::map(arrow::utf8(), arrow::field("value", arrow::int64()))'
    )
    assert arrow_type_expression("Spot", NESTED_TYPES) == (
        'arrow::struct_({arrow::field("x", arrow::int32()), '
        'arrow::field("tags", arrow::list(arrow::field("element", arrow::utf8())))})'
    )


def test_arrow_type_expression_renames_the_fields_of_a_struct() -> None:
    """A field is stored under the name that the file is to give it."""
    names = {"spot.x": "across", "spot.tags.element": "ignored"}

    assert arrow_type_expression("Spot", NESTED_TYPES, names, "spot") == (
        'arrow::struct_({arrow::field("across", arrow::int32()), '
        'arrow::field("tags", arrow::list(arrow::field("element", arrow::utf8())))})'
    )

    # The names are keyed by the flattened key, so another column keeps its own.
    assert arrow_type_expression("Spot", NESTED_TYPES, names, "other") == (
        'arrow::struct_({arrow::field("x", arrow::int32()), '
        'arrow::field("tags", arrow::list(arrow::field("element", arrow::utf8())))})'
    )


def test_aggregate_includes() -> None:
    """A map asks for the header of the container that holds its pairs."""
    assert "vector" in aggregate_includes(NESTED_TYPES["Tags"]).std
    assert "map" in aggregate_includes(NESTED_TYPES["Counts"]).std
    assert "unordered_map" not in aggregate_includes(NESTED_TYPES["Counts"]).std

    unordered = Map(
        name="Counts", key=ScalarType.str, value=ScalarType.i64, is_unordered=True
    )
    assert "unordered_map" in aggregate_includes(unordered).std


def test_generate_declares_a_type_before_the_tables_that_hold_it(
    tmp_path: Path,
) -> None:
    """A definition only ever names what an earlier definition declared."""
    header = generate_into(tmp_path, AGGREGATES_EXAMPLE)

    for declaration in (
        "using Keywords = std::vector<std::string>;",
        "using Ids = std::map<std::string, std::string>;",
        "using CitationsByYear = std::unordered_map<std::int64_t, std::uint32_t>;",
        "struct Biblio {",
        "using Topics = std::vector<TopicScore>;",
    ):
        assert header.count(declaration) == 1, declaration

    assert header.index("struct TopicScore {") < header.index("using Topics =")
    assert header.index("using Topics =") < header.index("struct Work {")
    assert header.index("struct Work {") < header.index("class WorkParquetReader {")

    # The containers the types are held in are included once.
    assert header.count("#include <map>") == 1
    assert header.count("#include <unordered_map>") == 1


def test_render_parquet_reader_reads_a_nested_column() -> None:
    """A column of an aggregate type is read level by level."""
    header = render_parquet_reader(NESTED_READER, NESTED_TABLE, NESTED_TYPES)

    # A nested column is stored as several leaves, so the leaves are projected.
    assert "std::vector<int> leaf_columns(" in header
    assert "const std::vector<int> columns = leaf_columns({" in header
    assert "field_index(*schema," not in header

    # Every part of the table is pointed at the array holding it.
    assert 'bind_tags(*batch.column(1), "tags");' in header
    assert "array_tags_ = as_list(source, where);" in header
    assert "array_counts_ = as_map(source, where);" in header
    assert "const arrow::StructArray& array = *as_struct(source, where);" in header

    # A field is looked for under the name the file gives it.
    assert 'bind_spot_x(*field_of(array, "across", where),' in header
    assert 'bind_spot_tags(*field_of(array, "tags", where),' in header

    # The value of a row is read out of those arrays.
    assert "Tags read_tags(std::int64_t i) const {" in header
    assert "Counts read_counts(std::int64_t i) const {" in header
    assert "Spot read_spot(std::int64_t i) const {" in header
    assert "            .x = array_spot_x_->Value(i)," in header
    assert "            .tags = read_spot_tags(i)," in header
    assert (
        "                read_tags(i),\n                read_counts(i),\n"
        "                read_spot(i));" in header
    )


def test_render_parquet_reader_null_handling_of_a_nested_column() -> None:
    """A part that has no default is a part that holds no null."""
    header = render_parquet_reader(NESTED_READER, NESTED_TABLE, NESTED_TYPES)

    # 'tags.element' has a default, and the parts around it do not.
    assert (
        'array_tags_element_->IsNull(j) ? std::string("n/a") '
        ": array_tags_element_->GetString(j)" in header
    )
    assert "if (array_spot_x_->null_count() != 0) [[unlikely]] {" in header
    assert "if (array_tags_element_->null_count() != 0)" not in header

    # An aggregate takes no default; a null one is read as the empty value.
    assert "        if (array_tags_->IsNull(i)) {\n            return value;" in header


def test_render_parquet_reader_names_a_column_in_the_file() -> None:
    """A reader looks for the name the file gives a column."""
    reader = ParquetReader(
        name="PointParquetReader", table="Point", name_in_file={"id": "ident"}
    )

    header = render_parquet_reader(reader, TABLE)

    assert 'field_index(*schema, "ident", arrow::uint32()),' in header
    assert 'if (schema.field(0)->name() != "ident") [[unlikely]] {' in header
    assert "column_id->Value(i)," in header


def test_render_parquet_reader_escapes_the_name_in_the_file() -> None:
    """A file names a column however it likes; the header still compiles."""
    reader = ParquetReader(
        name="PointParquetReader", table="Point", name_in_file={"id": 'a"b\\c'}
    )

    header = render_parquet_reader(reader, TABLE)

    assert r'field_index(*schema, "a\"b\\c", arrow::uint32()),' in header
    assert r'->name() != "a\"b\\c")' in header


def test_render_parquet_writer_names_a_nested_column_in_the_file() -> None:
    """A writer builds the names the file is to carry, at every level."""
    writer = ParquetWriter(
        name="RowParquetWriter",
        table="Row",
        name_in_file={"spot": "place", "spot.x": "across"},
    )

    header = render_parquet_writer(writer, NESTED_TABLE, NESTED_TYPES)

    # The column, and the field below it, are written under their names.
    assert 'arrow::field("place", arrow::struct_({arrow::field("across"' in header
    assert 'arrow::field("tags", arrow::list(arrow::field("element"' in header

    # The builder of the column builds the same names as the schema.
    assert (
        '            arrow::struct_({arrow::field("across", arrow::int32()), '
        'arrow::field("tags", arrow::list(arrow::field("element", arrow::utf8())))}),'
        in header
    )

    # The C++ members keep the names that the table and the struct give them.
    assert "        for (const auto& value : table.spot) {" in header
    assert "        append_spot_tags(value.tags);" in header


def test_render_parquet_writer_escapes_the_name_in_the_file() -> None:
    """A file names a column however it likes; the header still compiles."""
    writer = ParquetWriter(
        name="PointParquetWriter", table="Point", name_in_file={"id": 'a"b\\c'}
    )

    header = render_parquet_writer(writer, TABLE)

    assert r'arrow::field("a\"b\\c", arrow::uint32()),' in header


def test_render_csv_writer_escapes_the_name_in_the_file() -> None:
    """A file names a column however it likes; the header still compiles."""
    writer = CsvWriter(
        name="PointCsvWriter", table="Point", name_in_file={"id": 'a"b\\c'}
    )

    header = render_csv_writer(writer, TABLE)

    assert r'arrow::field("a\"b\\c", arrow::uint32()),' in header


def test_render_parquet_writer_builds_a_nested_column() -> None:
    """A column of an aggregate type is built level by level."""
    header = render_parquet_writer(NESTED_WRITER, NESTED_TABLE, NESTED_TYPES)

    assert (
        'arrow::field("tags", arrow::list(arrow::field("element", arrow::utf8()))),'
        in header
    )

    # The builders below a column are handed to the builder of the column.
    assert "std::shared_ptr<arrow::StringBuilder> builder_tags_element_ =" in header
    assert "std::shared_ptr<arrow::ListBuilder> builder_tags_ =" in header
    assert (
        "                                             builder_tags_element_," in header
    )
    assert "std::shared_ptr<arrow::MapBuilder> builder_counts_ =" in header
    assert "std::shared_ptr<arrow::StructBuilder> builder_spot_ =" in header

    # One row at a time is appended to them, and the batch is finished at once.
    assert "        for (const auto& value : table.tags) {\n" in header
    assert "            append_tags(value);" in header
    assert "    void append_tags(const Tags& value) {" in header
    assert "        for (const auto& [key, item] : value) {" in header
    assert "        append_spot_tags(value.tags);" in header
    assert "check(builder_tags_->Finish(&column_tags)," in header

    # A scalar column is still built by a builder of the batch it is written in.
    assert "arrow::UInt32Builder builder_id;" in header


def test_generate_defines_every_class_over_a_nested_table(tmp_path: Path) -> None:
    """The example of the aggregate types generates all of its classes."""
    header = generate_into(tmp_path, AGGREGATES_EXAMPLE)

    for declaration in (
        "class WorkParquetReader {",
        "class WorkSummaryParquetReader {",
        "class WorkParquetWriter {",
        "class WorkExportParquetWriter {",
        "class WorkSummaryCsvWriter {",
    ):
        assert header.count(declaration) == 1, declaration

    # The writer that renames writes the names that the reader looks for,
    # and the one that does not writes the names of the specification.
    assert 'arrow::field("display_name", arrow::utf8())' in header
    assert 'arrow::field("name", arrow::utf8())' in header

    # A reader of a nested table reaches for the schema of the Parquet file.
    assert "#include <parquet/schema.h>" in header
